version: '3.1'
services:

  app:
    container_name: CRUD_WEBAPP_APP
    image: crudwebapp
    build: .
    command: sh -c "sleep 30s; python3 ./backend.py"
    ports:
      - 5000:5000
    depends_on:
     - db
  db:
    container_name: CRUD_WEBAPP_DB
    image: mariadb
    restart: always
    environment:
    - MARIADB_ROOT_PASSWORD=root
    - MARIADB_USER=backend
    - MARIADB_PASSWORD=backend.MARIADB.22
    - MARIADB_DATABASE=backend
    volumes:
      - ./db:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d 
    ports:
      - 3306:3306
